import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToasterProvider from '@/components/providers/ToasterProvider'
import {SessionProvider} from "next-auth/react"
import { Session } from 'next-auth'
import AuthProvider from '@/components/providers/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: any
}) {
  return (
      <html className='' lang="en">
          <body className={inter.className}>
            <AuthProvider>
              <ToasterProvider/>
              {children}
            </AuthProvider>
          </body>
      </html>
  )
}